# Generated by Django 5.0 on 2025-12-04 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiktok_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('date', models.DateField(db_index=True, help_text='Date of this analytics snapshot')),
                ('follower_count', models.IntegerField(default=0, help_text='Total followers on this date')),
                ('following_count', models.IntegerField(default=0, help_text='Total following on this date')),
                ('video_count', models.IntegerField(default=0, help_text='Total videos on this date')),
                ('total_likes', models.BigIntegerField(default=0, help_text='Total likes across all videos')),
                ('total_views', models.BigIntegerField(default=0, help_text='Total views across all videos')),
                ('total_shares', models.BigIntegerField(default=0, help_text='Total shares across all videos')),
                ('total_comments', models.BigIntegerField(default=0, help_text='Total comments across all videos')),
                ('follower_growth', models.IntegerField(default=0, help_text='Change in followers since previous day')),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Engagement rate percentage', max_digits=5)),
                ('tiktok_account', models.ForeignKey(help_text='TikTok account these analytics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='tiktok_accounts.tiktokaccount')),
            ],
            options={
                'verbose_name': 'Account Analytics',
                'verbose_name_plural': 'Account Analytics',
                'db_table': 'account_analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['tiktok_account', 'date'], name='account_ana_tiktok__b27ab8_idx'), models.Index(fields=['date'], name='account_ana_date_b53c8b_idx')],
                'unique_together': {('tiktok_account', 'date')},
            },
        ),
    ]
