# Generated by Django 5.0 on 2025-12-04 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiktok_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('queued', 'In Queue'), ('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Current status of the post', max_length=20)),
                ('caption', models.TextField(help_text='Post caption (max 2200 chars per TikTok limits)', max_length=2200)),
                ('hashtags', models.JSONField(default=list, help_text='List of hashtags')),
                ('mentions', models.JSONField(default=list, help_text='List of mentioned users')),
                ('privacy_level', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('private', 'Private')], default='public', help_text='Post privacy setting', max_length=20)),
                ('scheduled_time', models.DateTimeField(db_index=True, help_text='When to publish the post')),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for scheduled_time', max_length=50)),
                ('published_at', models.DateTimeField(blank=True, help_text='When the post was actually published', null=True)),
                ('tiktok_video_id', models.CharField(blank=True, help_text="TikTok's video ID after publishing", max_length=100, null=True, unique=True)),
                ('video_url', models.URLField(blank=True, help_text='URL to the published TikTok video', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if publishing failed', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of times publishing has been retried')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retry attempts')),
                ('tiktok_account', models.ForeignKey(help_text='TikTok account to publish to', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='tiktok_accounts.tiktokaccount')),
            ],
            options={
                'verbose_name': 'Scheduled Post',
                'verbose_name_plural': 'Scheduled Posts',
                'db_table': 'scheduled_posts',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='PublishHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('attempt_number', models.IntegerField(help_text='Attempt number (1, 2, 3, etc.)')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the publish attempt started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the publish attempt completed', null=True)),
                ('success', models.BooleanField(default=False, help_text='Whether the publish was successful')),
                ('error_code', models.CharField(blank=True, help_text='Error code if failed', max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('api_response', models.JSONField(blank=True, help_text='Full API response from TikTok', null=True)),
                ('http_status', models.IntegerField(blank=True, help_text='HTTP status code from API', null=True)),
                ('scheduled_post', models.ForeignKey(help_text='Post that was attempted to publish', on_delete=django.db.models.deletion.CASCADE, related_name='publish_attempts', to='content.scheduledpost')),
            ],
            options={
                'verbose_name': 'Publish History',
                'verbose_name_plural': 'Publish Histories',
                'db_table': 'publish_history',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('thumbnail', 'Thumbnail')], help_text='Type of media file', max_length=20)),
                ('file_path', models.CharField(help_text='Path to the media file', max_length=500)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_mime_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('duration', models.IntegerField(blank=True, help_text='Video duration in seconds', null=True)),
                ('width', models.IntegerField(blank=True, help_text='Video/image width in pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Video/image height in pixels', null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether media has been processed')),
                ('thumbnail_path', models.CharField(blank=True, help_text='Path to generated thumbnail', max_length=500, null=True)),
                ('scheduled_post', models.ForeignKey(help_text='Post this media belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='content.scheduledpost')),
            ],
            options={
                'verbose_name': 'Post Media',
                'verbose_name_plural': 'Post Media',
                'db_table': 'post_media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledpost',
            index=models.Index(fields=['status', 'scheduled_time'], name='scheduled_p_status_39a7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpost',
            index=models.Index(fields=['tiktok_account', 'status'], name='scheduled_p_tiktok__b057d9_idx'),
        ),
        migrations.AddIndex(
            model_name='publishhistory',
            index=models.Index(fields=['scheduled_post', 'attempt_number'], name='publish_his_schedul_56ee97_idx'),
        ),
        migrations.AddIndex(
            model_name='publishhistory',
            index=models.Index(fields=['started_at'], name='publish_his_started_f76257_idx'),
        ),
        migrations.AddIndex(
            model_name='publishhistory',
            index=models.Index(fields=['success'], name='publish_his_success_6eb748_idx'),
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['scheduled_post', 'media_type'], name='post_media_schedul_ba0cf3_idx'),
        ),
    ]
