# Generated by Django 5.0 on 2025-12-06 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_add_analytics_to_publish_history"),
        ("tiktok_accounts", "0004_add_accounts_list_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="postmedia",
            name="post_media_schedul_ba0cf3_idx",
        ),
        migrations.RemoveIndex(
            model_name="publishhistory",
            name="publish_his_schedul_56ee97_idx",
        ),
        migrations.RemoveIndex(
            model_name="publishhistory",
            name="publish_his_started_f76257_idx",
        ),
        migrations.RemoveIndex(
            model_name="publishhistory",
            name="publish_his_success_6eb748_idx",
        ),
        migrations.RemoveIndex(
            model_name="scheduledpost",
            name="scheduled_p_tiktok__b057d9_idx",
        ),
        migrations.RenameIndex(
            model_name="publishhistory",
            new_name="publish_his_post_id_4e91f2_idx",
            old_fields=("post", "account"),
        ),
        migrations.RenameIndex(
            model_name="scheduledpost",
            new_name="scheduled_p_user_id_4db421_idx",
            old_fields=("user", "status"),
        ),
        migrations.AlterIndexTogether(
            name="scheduledpost",
            index_together=set(),
        ),
        migrations.AlterField(
            model_name="postmedia",
            name="post",
            field=models.ForeignKey(
                help_text="Post this media belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="content.scheduledpost",
            ),
        ),
        migrations.AlterField(
            model_name="publishhistory",
            name="post",
            field=models.ForeignKey(
                help_text="Post that was attempted to publish",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publish_history",
                to="content.scheduledpost",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledpost",
            name="description",
            field=models.TextField(
                help_text="Post description (max 2200 chars per TikTok limits)",
                max_length=2200,
            ),
        ),
        migrations.AddIndex(
            model_name="postmedia",
            index=models.Index(
                fields=["post", "media_type"], name="post_media_post_id_4d5f3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publishhistory",
            index=models.Index(fields=["status"], name="publish_his_status_1b2f11_idx"),
        ),
    ]
