# Generated by Django 5.0 on 2025-12-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_remove_postmedia_post_media_schedul_ba0cf3_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledpost",
            name="max_retries",
            field=models.IntegerField(
                default=3, help_text="Maximum number of retry attempts"
            ),
        ),
        migrations.AddField(
            model_name="scheduledpost",
            name="retry_count",
            field=models.IntegerField(
                default=0, help_text="Number of publish attempts made"
            ),
        ),
        migrations.AddField(
            model_name="scheduledpost",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Timezone for scheduled_time (e.g., 'America/New_York')",
                max_length=50,
            ),
        ),
    ]
