# Generated by Django 5.0 on 2025-12-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_add_slideshow_fields_to_post_media"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="postmedia",
            new_name="post_media_post_id_9bb454_idx",
            old_name="post_media_post_id_slideshow_idx",
        ),
    ]
