# Generated by Django 5.0 on 2025-12-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content",
            "0007_rename_post_media_post_id_slideshow_idx_post_media_post_id_9bb454_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmedia",
            name="post",
            field=models.ForeignKey(
                blank=True,
                help_text="Post this media belongs to (optional for standalone uploads)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="content.scheduledpost",
            ),
        ),
    ]
