# Generated by Django 5.0 on 2025-12-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_allow_null_post_in_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledpost",
            name="privacy_level",
            field=models.CharField(
                choices=[
                    ("public_to_everyone", "Public"),
                    ("mutual_follow_friends", "Friends"),
                    ("self_only", "Private"),
                ],
                default="public_to_everyone",
                help_text="Post privacy setting (TikTok API values)",
                max_length=25,
            ),
        ),
    ]
