# Generated by Django 5.0 on 2025-12-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_update_privacy_level_tiktok_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledpost",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("slideshow", "Slideshow"),
                    ("photo", "Photo"),
                ],
                default="video",
                help_text="Type of post content",
                max_length=20,
            ),
        ),
    ]
