# Generated by Django 5.0 on 2025-12-04 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('tiktok_user_id', models.CharField(db_index=True, help_text="TikTok's unique user ID", max_length=100, unique=True)),
                ('username', models.CharField(help_text='TikTok username', max_length=100)),
                ('display_name', models.CharField(help_text='TikTok display name', max_length=200)),
                ('avatar_url', models.URLField(blank=True, help_text='Profile picture URL', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Token Expired'), ('revoked', 'Access Revoked'), ('error', 'Error')], db_index=True, default='active', help_text='Account connection status', max_length=20)),
                ('access_token', models.TextField(help_text='Encrypted OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted OAuth refresh token', null=True)),
                ('token_expires_at', models.DateTimeField(help_text='When the access token expires')),
                ('follower_count', models.IntegerField(default=0, help_text='Number of followers')),
                ('following_count', models.IntegerField(default=0, help_text='Number of accounts being followed')),
                ('video_count', models.IntegerField(default=0, help_text='Total number of videos posted')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time account data was synced from TikTok', null=True)),
                ('user', models.ForeignKey(help_text='User who owns this TikTok account', on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TikTok Account',
                'verbose_name_plural': 'TikTok Accounts',
                'db_table': 'tiktok_accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'is_deleted'], name='tiktok_acco_user_id_55b878_idx'), models.Index(fields=['token_expires_at'], name='tiktok_acco_token_e_9b9688_idx')],
            },
        ),
    ]
