# Generated by Django 5.0 on 2025-12-04 10:58

import core.fields.encrypted_field
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tiktok_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiktokaccount",
            name="access_token",
            field=core.fields.encrypted_field.EncryptedTextField(
                help_text="Encrypted OAuth access token"
            ),
        ),
        migrations.AlterField(
            model_name="tiktokaccount",
            name="refresh_token",
            field=core.fields.encrypted_field.EncryptedTextField(
                blank=True, help_text="Encrypted OAuth refresh token", null=True
            ),
        ),
    ]
