# Generated by Django 5.0 on 2025-12-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiktok_accounts", "0002_alter_tiktokaccount_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiktokaccount",
            name="last_error",
            field=models.TextField(
                blank=True,
                help_text="Last error message from token refresh or API calls",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tiktokaccount",
            name="last_refreshed",
            field=models.DateTimeField(
                blank=True, help_text="Last time token was refreshed", null=True
            ),
        ),
    ]
