# Generated by Django 5.0 on 2025-12-05 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiktok_accounts", "0003_tiktokaccount_last_error_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tiktokaccount",
            index=models.Index(
                fields=["user", "status", "-created_at"], name="user_status_created_idx"
            ),
        ),
    ]
