# Generated by Django 5.0 on 2025-12-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiktok_accounts", "0004_add_accounts_list_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiktokaccount",
            name="avatar_url",
            field=models.URLField(
                blank=True, help_text="Profile picture URL", max_length=500, null=True
            ),
        ),
    ]
