# Generated by Django 5.0 on 2025-12-04 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Soft delete flag"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("publish", "Publish"),
                            ("schedule", "Schedule"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="Type of resource affected (e.g., 'TikTokAccount', 'ScheduledPost')",
                        max_length=100,
                    ),
                ),
                (
                    "resource_id",
                    models.UUIDField(
                        blank=True, help_text="ID of the affected resource", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="IP address of the user"),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Browser user agent string", null=True
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="JSON of changes made (before/after)",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata about the action",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "action", "created_at"],
                        name="audit_logs_user_id_831014_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_logs_resourc_bda8a6_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_logs_action_391715_idx",
                    ),
                ],
            },
        ),
    ]
